## Numpy Array
### Creating 1D Array

In [8]:
import numpy as np

## Normal Array
a = [1, 2, 3, 4, 5]

## Numpy Array
b = np.array([1, 2, 3, 4, 5])

## Display Array
print(b, '\n')

## Individual element access
print(b[1])


[1 2 3 4 5] 

2


### Multi-Dimensional Array

In [9]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Display Array
print(a, '\n')

## Access Individual Element
print(a[1], '\n')
print(a[2][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5 6] 

8


### Getting dimension / Shape if Array

In [45]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
c = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],[
        [10, 20],
        [30, 40],
        [50, 60]
    ]
])
## Show Dimension
## Gives depth/max dimension
print('Dimension of a:',a.ndim, '\n')
print('Dimension of b:',b.ndim, '\n')

## Gives Shape
print('Shape of a:',a.shape, '\n')
print('Shape of b:',b.shape, '\n')

## If all dimensions are not fully filled regularly, then numpy does not show dimension / shape
print('Dimension of c:',c.ndim, '\n')
print('Shape of c:',c.shape)

Dimension of a: 1 

Dimension of b: 2 

Shape of a: (5,) 

Shape of b: (3, 3) 

Dimension of c: 1 

Shape of c: (2,)


### Getting number of elements in Array

In [46]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Get number of elements
print(a.size, '\n')
print(b.size)

5 

9


### Data Type of elements in Array

In [49]:
import numpy as np
a = np.array([1.2, 2.3, 3.4, 4.5, 5.6])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype = float)

## Print Data Types of Elements
print(a.dtype)
print(b.dtype)

## Data type can be defined while defining array as done for c
print(c.dtype)

float64
int64
float64


### Zeros and Ones Matrix
Create matrix of all zeros/ones for the given shape

In [17]:
import numpy as np

## Fill 3x4 array with 0s
a = np.zeros((3, 4))

## Fill 4x3 array with 1s
b = np.ones((4, 3))

print(a, '\n')
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Custom Number full array
Create matrix of all the values filled with given number for provided shape

In [18]:
import numpy as np

## Fill 3x5 array with 4s
a = np.full((3, 5), 4)

print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


### Empty Matrix
Create matrix of provided shape with uninitialized values. Usually the values will look like junk.

In [20]:
import numpy as np

## Create empty matrix
a = np.empty((2, 7))

print(a)

[[4.64484131e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000]]


### Random Number
Create a matrix of given shape with random number $0 \le n \le 1$

In [21]:
import numpy as np

## 3x6 matrix of random numbers
a = np.random.random((3, 6))

print(a)

[[0.81830402 0.40728714 0.1661629  0.78176017 0.69523874 0.0474638 ]
 [0.31860297 0.04720085 0.53592058 0.78717893 0.73634145 0.02407926]
 [0.55849112 0.36377059 0.29023907 0.17318162 0.57651734 0.85867694]]


### Range of values
create a vector / 1D array for given start and end with step

In [37]:
import numpy as np

## Vector starting 0 to 50 with step of 5 excluing higher limit
a = np.arange(0, 51, 5)

## Linspace generate n number of evenly spaced values between the given range including higher limit
b = np.linspace(0, 50, 11)

print(a)
print(b)

[ 0  5 10 15 20 25 30 35 40 45 50]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


### Basic Mathematical operations
Mathematical operation on Numpy array is propagated to its elements unlike normal list where it change list length

In [28]:
import numpy as np

## Normal List
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]

## Numpy Array
c = np.array([1, 2, 3, 4, 5])
d = np.array([6, 7, 8, 9, 0])

## Output
print('Add Normal List:', a + b, '\n')

## Add Numpy Arrays
print('Add Numpy Array: ', c + d, '\n')

## Add Numpy array with Constant
print('Add Constant to Numpy Array:', 2 + c, '\n')

## Multiply List with constant number increase list length
print('List * constant:', a * 2, '\n')

## Multiply Numpy arrays with constant number
print('Numpy Array * Constant:', c * 2, '\n')

## Power on Numpy Array
print('Numpy Array ** 3:', c ** 3)

Add Normal List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0] 

Add Numpy Array:  [ 7  9 11 13  5] 

Add Constant to Numpy Array: [3 4 5 6 7] 

List * constant: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] 

Numpy Array * Constant: [ 2  4  6  8 10] 

Numpy Array ** 3: [  1   8  27  64 125]


### Equations with Numpy

In [33]:
import numpy as np

## X Co-ordinates
x = np.arange(0, 51, 5)
y1 = x**2 + 2*x  ## Y = X^2 + 2X
y2 = np.sin(x)   ## Y = Sin(X)

print(y1, '\n')
print(y2)

[   0   35  120  255  440  675  960 1295 1680 2115 2600] 

[ 0.         -0.95892427 -0.54402111  0.65028784  0.91294525 -0.13235175
 -0.98803162 -0.42818267  0.74511316  0.85090352 -0.26237485]


### Advance Mathematical Operations

In [20]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Trignometry
## Here angles are considered in radians. 
print("Sin(a): ", np.sin(a), '\n')
print("Cos(a): ", np.cos(a), '\n')
print("Tan(a): ", np.tan(a), '\n')
print("Sin^-1(a): ", np.arcsin(a), '\n')
print("Cos^-1(a): ", np.arccos(a), '\n')
print("Tan^-1(a): ", np.arctan(a), '\n')

## Exponential e^x
print("e^a: ", np.exp(a), '\n')

## Famous mathematics equation e^(pi)*i = -1
print("e^(pi*i): ", np.exp(np.pi * 1j), '\n')

## squareroot
print("Squareroot(a): ", np.sqrt(a), '\n')

## Logarithm
print("Natural Log(a) to base e: ", np.log(a), '\n')
print("Log(a) to base 10: ", np.log10(a), '\n')
print("Log(a) to base 2: ", np.log2(a), '\n')

Sin(a):  [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]] 

Cos(a):  [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]] 

Tan(a):  [[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]] 

Sin^-1(a):  [[1.57079633        nan        nan]
 [       nan        nan        nan]
 [       nan        nan        nan]] 

Cos^-1(a):  [[ 0. nan nan]
 [nan nan nan]
 [nan nan nan]] 

Tan^-1(a):  [[0.78539816 1.10714872 1.24904577]
 [1.32581766 1.37340077 1.40564765]
 [1.42889927 1.44644133 1.46013911]] 

e^a:  [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

e^(pi*i):  (-1+1.2246467991473532e-16j) 

Squareroot(a):  [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 

<ipython-input-20-72bee2028ca5>:14: RuntimeWarning: invalid value encountered in arcsin
  print("Sin^-1(a): ", np.arcsin(a), '\n')
<ipython-input-20-72bee2028ca5>:15: RuntimeWarning: invalid value encountered in arccos
  print("Cos^-1(a): ", np.arccos(a), '\n')


### Aggregate Functions

In [26]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Arithmatic Aggregate
print("Sum of elements: ", a.sum(), '\n')
print("Max of elements: ", a.max(), '\n')
print("Min of elements: ", a.min(), '\n')

## Statistical Aggregates
print("Mean/Average of elements: ", a.mean(), '\n')
print("Median of elements: ", np.median(a), '\n')
print("Standard Deviation of elements: ", np.std(a), '\n')

Sum of elements:  45 

Max of elements:  9 

Min of elements:  1 

Mean/Average of elements:  5.0 

Median of elements:  5.0 

Standard Deviation of elements:  2.581988897471611 



### Shape Manipulation 

In [33]:
import numpy as np

## Create 3x4 matrix i.e 12 elements
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

## Reshape
print("2x6 shape of array:\n", a.reshape((2, 6)), '\n')
print("6x2 shape of array:\n", a.reshape((6, 2)), '\n')
print("3x4 shape of array:\n", a.reshape((3, 4)), '\n')
print("4x3 shape of array:\n", a.reshape((4, 3)), '\n')
print("2x2x3 shape of array:\n", a.reshape((2, 2, 3)), '\n')
print("2x3x2 shape of array:\n", a.reshape((2, 3, 2)), '\n')

## Flaten to 1D array
print('Flattened array: \n', a.flatten(), '\n')

## Transpose row to column
print('Transpose of a:\n', a.transpose(), '\n')

## Flat Iterator is function which flatten teh array, but it generate flat list for iterations
for i in a.flat:
    print('Element: ',i)

2x6 shape of array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

6x2 shape of array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

3x4 shape of array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

4x3 shape of array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

2x2x3 shape of array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

2x3x2 shape of array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 

Flattened array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 

Transpose of a:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]] 

Element:  1
Element:  2
Element:  3
Element:  4
Element:  5
Element:  6
Element:  7
Element:  8
Element:  9
Element:  10
Element:  11
Element:  12


### Joining Arrays

In [40]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

b = np.array([
    [51, 52, 53, 54],
    [55, 56, 57, 58],
    [59, 60, 61, 62]
])

## Concatenate
c1 = np.concatenate((a, b))
print(f"Concatenate along 1st Dimension: Generated Shape - {c1.shape}\n {c1} \n")

c2 = np.concatenate((a, b), axis = 1)
print(f"Concatenate along 2nd Dimension: Generated Shape - {c2.shape}\n {c2} \n")

c3 = np.stack((a, b))
print(f"Concatenate along 1st Dimension: Generated Shape - {c3.shape}\n {c3} \n")

## Horizontal stack is same as concatenation on 2nd Dimension
c4 = np.hstack((a, b))
print(f"Horizontal Stack: Generated Shape - {c4.shape}\n {c4} \n")

## Vertical Stack is same as Concatenation along 1st Dimension
c5 = np.vstack((a, b))
print(f"Vertical Stack: Generated Shape - {c5.shape}\n {c5} \n")

Concatenate along 1st Dimension: Generated Shape - (6, 4)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]] 

Concatenate along 2nd Dimension: Generated Shape - (3, 8)
 [[ 1  2  3  4 51 52 53 54]
 [ 5  6  7  8 55 56 57 58]
 [ 9 10 11 12 59 60 61 62]] 

Concatenate along 1st Dimension: Generated Shape - (2, 3, 4)
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[51 52 53 54]
  [55 56 57 58]
  [59 60 61 62]]] 

Horizontal Stack: Generated Shape - (3, 8)
 [[ 1  2  3  4 51 52 53 54]
 [ 5  6  7  8 55 56 57 58]
 [ 9 10 11 12 59 60 61 62]] 

Vertical Stack: Generated Shape - (6, 4)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]] 



### Splitting Array

In [48]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

## Split method divide array in number of equal parts as given
for i, an in enumerate(np.split(a, 4)):
    print(f"Divided in 4 on 1st dimension - Array {i+1}: \n{an}\n")
    
for i, an in enumerate(np.split(a, 2)):
    print(f"Divided in 2 on 1st dimension - Array {i+1}: \n{an}\n")
    
for i, an in enumerate(np.split(a, 4, axis = 1)):
    print(f"Divided in 4 on 2nd dimension- Array {i+1}: \n{an}\n")
    
for i, an in enumerate(np.split(a, 2, axis = 1)):
    print(f"Divided in 2 on 2nd dimension- Array {i+1}: \n{an}\n")
    
## Horizontal split is same as splitting on 2nd Dimension
for i, an in enumerate(np.hsplit(a, 4)):
    print(f"Horizontally Divided in 4- Array {i+1}: \n{an}\n")

Divided in 4 on 1st dimension - Array 1: 
[[1 2 3 4]]

Divided in 4 on 1st dimension - Array 2: 
[[5 6 7 8]]

Divided in 4 on 1st dimension - Array 3: 
[[ 9 10 11 12]]

Divided in 4 on 1st dimension - Array 4: 
[[13 14 15 16]]

Divided in 2 on 1st dimension - Array 1: 
[[1 2 3 4]
 [5 6 7 8]]

Divided in 2 on 1st dimension - Array 2: 
[[ 9 10 11 12]
 [13 14 15 16]]

Divided in 4 on 2nd dimension- Array 1: 
[[ 1]
 [ 5]
 [ 9]
 [13]]

Divided in 4 on 2nd dimension- Array 2: 
[[ 2]
 [ 6]
 [10]
 [14]]

Divided in 4 on 2nd dimension- Array 3: 
[[ 3]
 [ 7]
 [11]
 [15]]

Divided in 4 on 2nd dimension- Array 4: 
[[ 4]
 [ 8]
 [12]
 [16]]

Divided in 2 on 2nd dimension- Array 1: 
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

Divided in 2 on 2nd dimension- Array 2: 
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Horizontally Divided in 4- Array 1: 
[[ 1]
 [ 5]
 [ 9]
 [13]]

Horizontally Divided in 4- Array 2: 
[[ 2]
 [ 6]
 [10]
 [14]]

Horizontally Divided in 4- Array 3: 
[[ 3]
 [ 7]
 [11]
 [15]]

Horizontally Divi

### Adding values, row to Array

In [2]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

b = [21, 22, 23, 24]

## Here a is 4x4 array with dimension 2 and b is 1x4 array with dimension 1
## So when we append b to a, numpy has to flatten the a
print(f'Append without changing dimensions: \n{np.append(a, b)}\n')

## So in order to append correctly, b should be same dimension as a
## and we achieve this by surrounding b in brackets [b]
print(f'Append without changing dimensions: \n{np.append(a, [b], axis = 0)}\n')

## Or add to particular index using insert method
print(f"Insert row in index 1: \n{np.insert(a, 1, b, axis = 0)}\n")

## Column can be added using axis
print(f"Insert column in index 1: \n{np.insert(a, 1, b, axis = 1)}\n")

Append without changing dimensions: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 21 22 23 24]

Append without changing dimensions: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [21 22 23 24]]

Insert row in index 1: 
[[ 1  2  3  4]
 [21 22 23 24]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Insert column in index 1: 
[[ 1 21  2  3  4]
 [ 5 22  6  7  8]
 [ 9 23 10 11 12]
 [13 24 14 15 16]]

