## Numpy Array
### Creating 1D Array

In [8]:
import numpy as np

## Normal Array
a = [1, 2, 3, 4, 5]

## Numpy Array
b = np.array([1, 2, 3, 4, 5])

## Display Array
print(b, '\n')

## Individual element access
print(b[1])


[1 2 3 4 5] 

2


### Multi-Dimensional Array

In [9]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Display Array
print(a, '\n')

## Access Individual Element
print(a[1], '\n')
print(a[2][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5 6] 

8


### Getting dimension / Shape if Array

In [45]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
c = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],[
        [10, 20],
        [30, 40],
        [50, 60]
    ]
])
## Show Dimension
## Gives depth/max dimension
print('Dimension of a:',a.ndim, '\n')
print('Dimension of b:',b.ndim, '\n')

## Gives Shape
print('Shape of a:',a.shape, '\n')
print('Shape of b:',b.shape, '\n')

## If all dimensions are not fully filled regularly, then numpy does not show dimension / shape
print('Dimension of c:',c.ndim, '\n')
print('Shape of c:',c.shape)

Dimension of a: 1 

Dimension of b: 2 

Shape of a: (5,) 

Shape of b: (3, 3) 

Dimension of c: 1 

Shape of c: (2,)


### Getting number of elements in Array

In [46]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Get number of elements
print(a.size, '\n')
print(b.size)

5 

9


### Data Type of elements in Array

In [49]:
import numpy as np
a = np.array([1.2, 2.3, 3.4, 4.5, 5.6])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype = float)

## Print Data Types of Elements
print(a.dtype)
print(b.dtype)

## Data type can be defined while defining array as done for c
print(c.dtype)

float64
int64
float64


### Mathematical operations
Mathematical operation on Numpy array is propagated to its elements unlike normal list where it change list length

In [28]:
import numpy as np

## Normal List
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]

## Numpy Array
c = np.array([1, 2, 3, 4, 5])
d = np.array([6, 7, 8, 9, 0])

## Output
print('Add Normal List:', a + b, '\n')

## Add Numpy Arrays
print('Add Numpy Array: ', c + d, '\n')

## Add Numpy array with Constant
print('Add Constant to Numpy Array:', 2 + c, '\n')

## Multiply List with constant number increase list length
print('List * constant:', a * 2, '\n')

## Multiply Numpy arrays with constant number
print('Numpy Array * Constant:', c * 2, '\n')

## Power on Numpy Array
print('Numpy Array ** 3:', c ** 3)

Add Normal List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0] 

Add Numpy Array:  [ 7  9 11 13  5] 

Add Constant to Numpy Array: [3 4 5 6 7] 

List * constant: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] 

Numpy Array * Constant: [ 2  4  6  8 10] 

Numpy Array ** 3: [  1   8  27  64 125]


### Zeros and Ones Matrix
Create matrix of all zeros/ones for the given shape

In [17]:
import numpy as np

## Fill 3x4 array with 0s
a = np.zeros((3, 4))

## Fill 4x3 array with 1s
b = np.ones((4, 3))

print(a, '\n')
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Custom Number full array
Create matrix of all the values filled with given number for provided shape

In [18]:
import numpy as np

## Fill 3x5 array with 4s
a = np.full((3, 5), 4)

print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


### Empty Matrix
Create matrix of provided shape with uninitialized values. Usually the values will look like junk.

In [20]:
import numpy as np

## Create empty matrix
a = np.empty((2, 7))

print(a)

[[4.64484131e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000]]


### Random Number
Create a matrix of given shape with random number $0 \le n \le 1$

In [21]:
import numpy as np

## 3x6 matrix of random numbers
a = np.random.random((3, 6))

print(a)

[[0.81830402 0.40728714 0.1661629  0.78176017 0.69523874 0.0474638 ]
 [0.31860297 0.04720085 0.53592058 0.78717893 0.73634145 0.02407926]
 [0.55849112 0.36377059 0.29023907 0.17318162 0.57651734 0.85867694]]


### Range of values
create a vector / 1D array for given start and end with step

In [37]:
import numpy as np

## Vector starting 0 to 50 with step of 5 excluing higher limit
a = np.arange(0, 51, 5)

## Linspace generate n number of evenly spaced values between the given range including higher limit
b = np.linspace(0, 50, 11)

print(a)
print(b)

[ 0  5 10 15 20 25 30 35 40 45 50]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


### Equations with Numpy

In [33]:
import numpy as np

## X Co-ordinates
x = np.arange(0, 51, 5)
y1 = x**2 + 2*x  ## Y = X^2 + 2X
y2 = np.sin(x)   ## Y = Sin(X)

print(y1, '\n')
print(y2)

[   0   35  120  255  440  675  960 1295 1680 2115 2600] 

[ 0.         -0.95892427 -0.54402111  0.65028784  0.91294525 -0.13235175
 -0.98803162 -0.42818267  0.74511316  0.85090352 -0.26237485]
