## Data Types
* Vector 
* Array
* Matrix
* List
* Data Frame

### Vectors
vectors are are sequence of values. It can be one of 5 Atomic classes
* Logical (TRUE / FALSE)
* Integer
* Numeric (Float)
* Complex (a + bi)
* Character (String)  
  
Vector is created by `c()` function

In [2]:
## Logical Vector
lv = c(TRUE, FALSE)
class(lv)

[1] "logical"

In [5]:
## Numeric Vector
nv = c(15, 8.32426343, 999999)
class(nv)

[1] "numeric"

In [6]:
## Integer Vector
iv = c(58L, 32L)
class(iv)

[1] "integer"

In [7]:
## Character vector
cv = c("Hello", "World")
class(cv)

[1] "character"

In [8]:
## Complex Vector
xv = c(3+5i, 2+9i)
class(xv)

[1] "complex"

In [11]:
## Mix Vectors
## If you mix different types, it converts all to single type
mv1 = c(3L, TRUE, FALSE, 3.1837282)
mv1  ## Everything is converted to Numeric

mv2 = c("Hello", FALSE, 56L, 3+5i)
mv2  ## Everything is converted to String

[1] 3.000000 1.000000 0.000000 3.183728

[1] "Hello" "FALSE" "56"    "3+5i"

In [12]:
## Range of Numeric Vector
rv = c(5:29)
rv

[1]  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29

### Matrix
Matrix is 2 dimensional array  
Matrix is created by `matrix()` function

In [26]:
## Creating Matrix
mtr = matrix(c(1:25), 5, 5)
mtr

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

### Array
Array is n dimensional setup of Data  
Array is created by `array()` function

In [28]:
## Creating an array
ar = array(c(10:34), dim = c(5, 5, 4, 2))
ar ## This generate a 4x2 array of 5x5 matrix

, , 1, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

, , 2, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

, , 3, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

, , 4, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

, , 1, 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

, , 2, 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

, , 3, 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

, , 4, 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   15   20   25   30
[2,]   11   16   21   26   31
[3,]   12   17   22   27   32
[4,]   13   18   23   28   33
[5,]   14   19   24   29   34

### List
Lists are similar as vector except List can store different data types without converting to single data type  
Lists are created by `list()` function

In [29]:
## Creating List
li = list("hello", TRUE, 15L, 3+5i, 3.14)
li

[[1]]
[1] "hello"

[[2]]
[1] TRUE

[[3]]
[1] 15

[[4]]
[1] 3+5i

[[5]]
[1] 3.14

### Data Frame
Data frame is 2 dimensional List which looks like a table storing data in Rows and Columns  
Data frame is created by `data.frame()` function

In [32]:
## Creating data frame
id = c(1:5)
name = c("Ashok", "Bela", "Janice", "Leo", "Praveen")
age = c(27L, 20L, 30L, 34L, 45L)
df = data.frame(id, name, age)
df

id name    age
1 1  Ashok   27 
2 2  Bela    20 
3 3  Janice  30 
4 4  Leo     34 
5 5  Praveen 45

In [34]:
## There are some built in data frames like follow
data.frame(airquality)

Ozone Solar.R Wind Temp Month Day
1    41   190      7.4 67   5      1 
2    36   118      8.0 72   5      2 
3    12   149     12.6 74   5      3 
4    18   313     11.5 62   5      4 
5    NA    NA     14.3 56   5      5 
6    28    NA     14.9 66   5      6 
7    23   299      8.6 65   5      7 
8    19    99     13.8 59   5      8 
9     8    19     20.1 61   5      9 
10   NA   194      8.6 69   5     10 
11    7    NA      6.9 74   5     11 
12   16   256      9.7 69   5     12 
13   11   290      9.2 66   5     13 
14   14   274     10.9 68   5     14 
15   18    65     13.2 58   5     15 
16   14   334     11.5 64   5     16 
17   34   307     12.0 66   5     17 
18    6    78     18.4 57   5     18 
19   30   322     11.5 68   5     19 
20   11    44      9.7 62   5     20 
21    1     8      9.7 59   5     21 
22   11   320     16.6 73   5     22 
23    4    25      9.7 61   5     23 
24   32    92     12.0 61   5     24 
25   NA    66     16.6 57   5     25 
26   NA   266     14.9 58   5     26 
27   NA    NA      8.0 57   5     27 
28   23    13     12.0 67   5     28 
29   45   252     14.9 81   5     29 
30  115   223      5.7 79   5     30 
⋮   ⋮     ⋮       ⋮    ⋮    ⋮     ⋮  
124 96    167      6.9 91   9      1 
125 78    197      5.1 92   9      2 
126 73    183      2.8 93   9      3 
127 91    189      4.6 93   9      4 
128 47     95      7.4 87   9      5 
129 32     92     15.5 84   9      6 
130 20    252     10.9 80   9      7 
131 23    220     10.3 78   9      8 
132 21    230     10.9 75   9      9 
133 24    259      9.7 73   9     10 
134 44    236     14.9 81   9     11 
135 21    259     15.5 76   9     12 
136 28    238      6.3 77   9     13 
137  9     24     10.9 71   9     14 
138 13    112     11.5 71   9     15 
139 46    237      6.9 78   9     16 
140 18    224     13.8 67   9     17 
141 13     27     10.3 76   9     18 
142 24    238     10.3 68   9     19 
143 16    201      8.0 82   9     20 
144 13    238     12.6 64   9     21 
145 23     14      9.2 71   9     22 
146 36    139     10.3 81   9     23 
147  7     49     10.3 69   9     24 
148 14     20     16.6 63   9     25 
149 30    193      6.9 70   9     26 
150 NA    145     13.2 77   9     27 
151 14    191     14.3 75   9     28 
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

## Operators
* Arithmatic
* Assignment
* Logical
* Relational

### Arithmatic Operator
* Addition (a + b)
* Substraction (a - b)
* Multiplication (a * b)
* Division (a / b)
* Exponent (a ^ b)
* Modulus (a %% b)
* Floor Division (a %/% b)

In [35]:
## Example
print(22 + 7)
print(22 - 7)
print(22 * 7)
print(22 / 7)
print(22 ^ 7)
print(22 %% 7)
print(22 %/% 7)

[1] 29
[1] 15
[1] 154
[1] 3.142857
[1] 2494357888
[1] 1
[1] 3


### Relational Operator
Used for comparision and return bolean value

In [36]:
## Example
print(22 == 7)
print(22 != 7)
print(22 > 7)
print(22 < 7)
print(22 >= 7)
print(22 <= 7)

[1] FALSE
[1] TRUE
[1] TRUE
[1] FALSE
[1] TRUE
[1] FALSE


### Assignment Operator
* Left Assignment
    * x = 2
    * x <- 2
* Right Assignment
    * 2 -> x

In [38]:
## Example
x = 2
print(x)

x <- 5
print(x)

10 -> x
print(x)

[1] 2
[1] 5
[1] 10


### Logical Operator
* Logical And (a & b)
* Logical Or (a | b)
* Logical Not (!a)

In [40]:
## Example
op1 = c(TRUE, FALSE, FALSE, TRUE)
op2 = c(TRUE, TRUE, FALSE, FALSE)
print(op1 & op2)
print(op1 | op2)
print(! op2)

[1]  TRUE FALSE FALSE FALSE
[1]  TRUE  TRUE FALSE  TRUE
[1] FALSE FALSE  TRUE  TRUE


## Conditional Statements
Execute a piece of code if some condition is true

#### If Condition
`if (logical statement)
    {
        // Expression if True
    }
else if (Other logic statement)
    {
        // Expression if True
    }
else
    {
        // Expression if none is true
    }`
    
#### Switch Case
`switch (Expression, 
    Case 1 = Expression 1,
    Case 2 = Expression 2,
    Case 3 = Expression 3
    Default Statement)`

In [42]:
## Example for IF Statement
v1 = 25
v2 = 15

if ( v1 + v2 > 100 ) {
    print("Greater than 100")
} else if (v1 + v2 > 50) {
    print("Greater than 50")
} else {
    print("Less than 50")
}

[1] "Less than 50"


In [44]:
## Example for Switch Case
v = 4
switch (v 
       , '1' = print('Monday')
       , '2' = print('Tuesday')
       , '3' = print('Wednesday')
       , '4' = print('Thursday')
       , '5' = print('Friday')
       , '6' = print('Saturday')
       , '7' = print('Sunday')
       , print('Day not known'))

[1] "Thursday"


## Loops
Run a piece of code multiple times
* repeat (repeat indefinetely. This can be ended by an if statement with break keyword)
* while (Repeat condition until the condition is false)
* for

### Repeat Loop
`repeat {
    // Expression
    if (condition) {
        break
    }
}`

Execute the expression until the condition is true. If condition is not given, it will run infinitely.

In [48]:
## Example of Repeat Loop
v = 5
repeat {
    print(v)
    
    v = v + 2
    
    if (v > 12) {
        break
    }
}

[1] 5
[1] 7
[1] 9
[1] 11


### While Loop
`while (condition) {
    //Expression
} `
  
If the condition fail in first instance, it will exit instantaneously without executing anything.

In [49]:
## Example of while loop
v = 5
while (v < 12) {
    print (v)
    v = v + 2
}

[1] 5
[1] 7
[1] 9
[1] 11


### For Loop
Iterate over a vector

`for (x in vector) {
    // Expression
}`

In [56]:
## Example of For loop
for ( x in 1:10) {
    print(x ^ 2)
}

for (y in list('Hello', 'World', 3+5i, 12L)) {
    print(y)
}

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25
[1] 36
[1] 49
[1] 64
[1] 81
[1] 100
[1] "Hello"
[1] "World"
[1] 3+5i
[1] 12


## Strings

String data type allow following basic operations

### Concatenation
`paste(str1, str2)`

### Character Count
`nchar(str1)`

### Change Case
`toupper(str1)
tolower(str1)`

### Substring
`substring(str1, start_pos, end_pos)`

In [61]:
s1 = 'Hello'
s2 = 'World'

## Concatenate string
print( paste(s1, s2) )

## Character count
print( nchar(s1) )

## Change case
print( tolower(s1))

## Substring
print( substring(s1, 2, 4) )

[1] "Hello World"
[1] 5
[1] "hello"
[1] "ell"


## Functions
`func_name <- function(inp_var) {
    // Expression
} `

In [70]:
## Function for fibonachi series
fibo <- function(a) {
    v1 = 0
    v2 = 1
    for (i in 0:(a-1)) {
        if (i == 0) {
            print(0)
        } else if (i == 1) {
            print(1)
        } else {
            v3 <- v2 + v1
            print(v3)
            v1 <- v2
            v2 <- v3
        }
    }
}

fibo(5)
fibo(10)

[1] 0
[1] 1
[1] 1
[1] 2
[1] 3
[1] 0
[1] 1
[1] 1
[1] 2
[1] 3
[1] 5
[1] 8
[1] 13
[1] 21
[1] 34
